defaultEntryPoints = ["http", "https"]
[web] 
    address = ":8080" 
    [web.auth.basic] 
        users = ["mmakov:$apr1$AAgPbZdc$Y.0blMlr4J42lKXVGbizq."]
[entryPoints] 
    [entryPoints.http] 
        address = ":80" 
    [entryPoints.http.redirect] 
        entryPoint = "https" 
    [entryPoints.https] 
        address = ":443" 
    [entryPoints.https.tls]
[acme] 
    email = "makovetskiy@gmail.com" 
    storage = "acme.json" 
    entryPoint = "https" 
    onHostRule = true 
    onDemand = false

